---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install awscli
  apt:
    name: awscli
    state: present

- name: Install kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm -f kubectl

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Start and enable Docker
  service:
    name: docker
    enabled: yes
    state: started
