apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      receiver: 'email-alerts'
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
      - name: 'email-alerts'
        email_configs:
          - to: 'syamala.kadimi@gmail.com'
            from: 'syamala.kadimi@gmail.com'
            smarthost: 'smtp.gmail.com:587'
            auth_username: 'syamala.kadimi@gmail.com'
            auth_identity: 'syamala.kadimi@gmail.com'
            auth_password: 'your_app_password'
